name: CD

# secrets setup:
# - NODE_AUTH_TOKEN: ${{secrets.npm_token}}
# - GITHUB_TOKEN (inherent in the CI and no need to set up, used by standalone.js + gh releaser)

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-before-publish:
    uses: ./.github/workflows/ci.yml
  publish:
    needs: build-before-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17.x
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install
      - run: yarn build
      - run: yarn hygen:build -- init self # smoke test the built bundle
      - run: npm publish # add the package to npm
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
      - run: yarn standalone # creates binaries
      - name: Github Release # adds the binaries to github release
        uses: softprops/action-gh-release@v1
        with:
          files: "standalone/*"
      - name: Extract version
        id: extract-version
        run: |
          printf "::set-output name=%s::%s\n" tag-name "${GITHUB_REF#refs/tags/}"
      - uses: mislav/bump-homebrew-formula-action@v1
        with:
          formula-path: hygen.rb
          homebrew-tap: jondot/homebrew-tap
          download-url: "https://github.com/jondot/hygen/releases/download/${{ steps.extract-version.outputs.tag-name }}/hygen.macos.${{ steps.extract-version.outputs.tag-name }}.tar.gz"
          commit-message: updating formula for Hygen
        env:
          COMMITTER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
